import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."enum_pages_page_type" ADD VALUE 'members';
  ALTER TYPE "public"."enum_pages_page_type" ADD VALUE 'training-leads';
  ALTER TYPE "public"."enum_pages_page_type" ADD VALUE 'nodal-officers';
  ALTER TYPE "public"."enum__pages_v_version_page_type" ADD VALUE 'members';
  ALTER TYPE "public"."enum__pages_v_version_page_type" ADD VALUE 'training-leads';
  ALTER TYPE "public"."enum__pages_v_version_page_type" ADD VALUE 'nodal-officers';
  CREATE TABLE "pages_contributor_form_labels_experience_options" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"value" varchar,
  	"label" varchar
  );
  
  CREATE TABLE "_pages_v_version_contributor_form_labels_experience_options" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"value" varchar,
  	"label" varchar,
  	"_uuid" varchar
  );
  
  CREATE TABLE "site_settings_category_labels" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"value" varchar NOT NULL,
  	"label" varchar NOT NULL
  );
  
  CREATE TABLE "site_settings_issuing_body_labels" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"value" varchar NOT NULL,
  	"label" varchar NOT NULL
  );
  
  CREATE TABLE "site_settings" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"site_title" varchar DEFAULT 'ARIFAC — Alliance of Reporting Entities in India for AML/CFT',
  	"site_description" varchar DEFAULT 'ARIFAC enables collaboration, capacity building, and coordinated action to strengthen India''s financial crime prevention ecosystem under the guidance of FIU-IND.',
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  ALTER TABLE "pages_blocks_regulatory_dashboard" ADD COLUMN "view_circular_label" varchar DEFAULT 'View Circular';
  ALTER TABLE "pages_blocks_featured_programs" ADD COLUMN "course_details_label" varchar DEFAULT 'Course Details';
  ALTER TABLE "pages" ADD COLUMN "membership_sections_benefits_eyebrow" varchar DEFAULT 'What ARIFAC Engagement Enables';
  ALTER TABLE "pages" ADD COLUMN "membership_sections_benefits_heading" varchar DEFAULT 'Capacity building and collaboration benefits for the financial intelligence ecosystem.';
  ALTER TABLE "pages" ADD COLUMN "membership_sections_benefits_description" varchar DEFAULT 'Benefits differ by engagement tier, with enhanced access for Members.';
  ALTER TABLE "pages" ADD COLUMN "membership_sections_responsibilities_eyebrow" varchar DEFAULT 'Obligations';
  ALTER TABLE "pages" ADD COLUMN "membership_sections_responsibilities_heading" varchar DEFAULT 'Member / Affiliate Responsibilities';
  ALTER TABLE "pages" ADD COLUMN "membership_sections_responsibilities_description" varchar DEFAULT 'Members are expected to maintain the highest standards of integrity, professionalism, and compliance.';
  ALTER TABLE "pages" ADD COLUMN "membership_sections_responsibilities_disclaimer" varchar DEFAULT 'Members must not disclose sensitive regulatory or transaction-related information, including Suspicious Transaction Reporting (STR)-related discussions or any confidential compliance data.';
  ALTER TABLE "pages" ADD COLUMN "membership_sections_validity_eyebrow" varchar DEFAULT 'Terms';
  ALTER TABLE "pages" ADD COLUMN "membership_sections_validity_heading" varchar DEFAULT 'Validity & Renewal';
  ALTER TABLE "pages" ADD COLUMN "membership_sections_fees_eyebrow" varchar DEFAULT 'Pricing';
  ALTER TABLE "pages" ADD COLUMN "membership_sections_fees_heading" varchar DEFAULT 'Fees';
  ALTER TABLE "pages" ADD COLUMN "membership_sections_fees_description" varchar DEFAULT 'Membership fees are determined by your organisation''s self-declared annual turnover or Assets Under Management (AUM), as applicable. All fees are exclusive of taxes and subject to revision.';
  ALTER TABLE "pages" ADD COLUMN "membership_sections_turnover_label" varchar DEFAULT 'Turnover-Based';
  ALTER TABLE "pages" ADD COLUMN "membership_sections_aum_label" varchar DEFAULT 'AUM-Based';
  ALTER TABLE "pages" ADD COLUMN "membership_sections_fee_suffix" varchar DEFAULT '+ taxes';
  ALTER TABLE "pages" ADD COLUMN "membership_sections_turnover_column_header" varchar DEFAULT 'Turnover ₹';
  ALTER TABLE "pages" ADD COLUMN "membership_sections_aum_column_header" varchar DEFAULT 'AUM ₹';
  ALTER TABLE "pages" ADD COLUMN "membership_sections_fee_column_header" varchar DEFAULT 'Annual Fee';
  ALTER TABLE "pages" ADD COLUMN "learners_section_access_eyebrow" varchar DEFAULT 'Access';
  ALTER TABLE "pages" ADD COLUMN "learners_section_access_heading" varchar DEFAULT 'Building a foundation for you to learn, engage, and grow';
  ALTER TABLE "pages" ADD COLUMN "learners_section_access_description" varchar DEFAULT 'Via access to:';
  ALTER TABLE "pages" ADD COLUMN "learners_section_cta_eyebrow" varchar DEFAULT 'Open & Free';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_personal_info_header" varchar DEFAULT 'Personal Information';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_contact_details_header" varchar DEFAULT 'Contact Details';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_professional_bg_header" varchar DEFAULT 'Professional Background';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_expertise_header" varchar DEFAULT 'Area of Expertise';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_expertise_instruction" varchar DEFAULT 'Select all that apply';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_contribution_header" varchar DEFAULT 'How You Can Contribute';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_contribution_label" varchar DEFAULT 'Tell us how you would like to contribute to ARIFAC';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_contribution_placeholder" varchar DEFAULT 'E.g. training delivery, content authoring, research, speaking at events, policy consultation...';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_linkedin_label" varchar DEFAULT 'LinkedIn Profile';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_linkedin_placeholder" varchar DEFAULT 'https://linkedin.com/in/...';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_submit_label" varchar DEFAULT 'Submit Application';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_success_heading" varchar DEFAULT 'Thank you for your interest';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_success_eyebrow" varchar DEFAULT 'Submitted';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_success_description" varchar DEFAULT 'We have received your application. Our team will review your profile and get back to you shortly.';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_why_contribute_header" varchar DEFAULT 'Why Contribute';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_first_name_label" varchar DEFAULT 'First Name';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_last_name_label" varchar DEFAULT 'Last Name';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_email_label" varchar DEFAULT 'Email Address';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_phone_label" varchar DEFAULT 'Phone Number';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_organisation_label" varchar DEFAULT 'Organisation';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_designation_label" varchar DEFAULT 'Designation';
  ALTER TABLE "pages" ADD COLUMN "contributor_form_labels_experience_label" varchar DEFAULT 'Years of Experience';
  ALTER TABLE "pages" ADD COLUMN "certifications_u_i_filter_title" varchar DEFAULT 'Filter Programmes';
  ALTER TABLE "pages" ADD COLUMN "certifications_u_i_search_label" varchar DEFAULT 'Search';
  ALTER TABLE "pages" ADD COLUMN "certifications_u_i_search_placeholder" varchar DEFAULT 'Title, focus, topic...';
  ALTER TABLE "pages" ADD COLUMN "certifications_u_i_level_label" varchar DEFAULT 'Level';
  ALTER TABLE "pages" ADD COLUMN "certifications_u_i_format_label" varchar DEFAULT 'Format';
  ALTER TABLE "pages" ADD COLUMN "certifications_u_i_clear_filters_label" varchar DEFAULT 'Clear Filters';
  ALTER TABLE "pages" ADD COLUMN "certifications_u_i_curriculum_label" varchar DEFAULT 'Curriculum';
  ALTER TABLE "pages" ADD COLUMN "certifications_u_i_live_label" varchar DEFAULT 'Live';
  ALTER TABLE "pages" ADD COLUMN "certifications_u_i_live_description" varchar DEFAULT 'This course is now live for employees of reporting entities, based on nominations received from their respective organisations.';
  ALTER TABLE "pages" ADD COLUMN "certifications_u_i_coming_soon_label" varchar DEFAULT 'Coming Soon';
  ALTER TABLE "pages" ADD COLUMN "certifications_u_i_no_results_message" varchar DEFAULT 'No courses match the selected filters. Try adjusting your search or filter selections.';
  ALTER TABLE "pages" ADD COLUMN "contact_form_labels_success_message" varchar DEFAULT 'Thank you! Your message has been sent successfully. We will get back to you shortly.';
  ALTER TABLE "pages" ADD COLUMN "contact_form_labels_error_message" varchar DEFAULT 'Oops! Something went wrong. Please try again later.';
  ALTER TABLE "pages" ADD COLUMN "contact_form_labels_name_label" varchar DEFAULT 'Full Name';
  ALTER TABLE "pages" ADD COLUMN "contact_form_labels_name_placeholder" varchar DEFAULT 'Enter your full name';
  ALTER TABLE "pages" ADD COLUMN "contact_form_labels_email_label" varchar DEFAULT 'Email Address';
  ALTER TABLE "pages" ADD COLUMN "contact_form_labels_email_placeholder" varchar DEFAULT 'Enter your email address';
  ALTER TABLE "pages" ADD COLUMN "contact_form_labels_phone_label" varchar DEFAULT 'Phone Number';
  ALTER TABLE "pages" ADD COLUMN "contact_form_labels_phone_placeholder" varchar DEFAULT 'Enter your phone number';
  ALTER TABLE "pages" ADD COLUMN "contact_form_labels_subject_label" varchar DEFAULT 'Subject';
  ALTER TABLE "pages" ADD COLUMN "contact_form_labels_subject_placeholder" varchar DEFAULT 'How can we help?';
  ALTER TABLE "pages" ADD COLUMN "contact_form_labels_message_label" varchar DEFAULT 'Message';
  ALTER TABLE "pages" ADD COLUMN "contact_form_labels_message_placeholder" varchar DEFAULT 'Write your message here...';
  ALTER TABLE "pages" ADD COLUMN "contact_form_labels_submit_label" varchar DEFAULT 'Send Message';
  ALTER TABLE "pages" ADD COLUMN "contact_form_labels_submitting_label" varchar DEFAULT 'Sending...';
  ALTER TABLE "pages" ADD COLUMN "members_labels_directory_eyebrow" varchar DEFAULT 'Member Directory';
  ALTER TABLE "pages" ADD COLUMN "members_labels_count_label" varchar DEFAULT 'Organisations';
  ALTER TABLE "pages" ADD COLUMN "members_labels_footer_label" varchar DEFAULT 'Member Organisations';
  ALTER TABLE "pages" ADD COLUMN "training_leads_content_section_eyebrow" varchar DEFAULT 'Expert Network';
  ALTER TABLE "pages" ADD COLUMN "training_leads_content_section_heading" varchar DEFAULT 'ARIFAC Training Lead Directory';
  ALTER TABLE "pages" ADD COLUMN "training_leads_content_section_description" varchar DEFAULT 'Domain specialists appointed across India''s financial ecosystem to lead certification, capacity building, and AML/CFT training initiatives.';
  ALTER TABLE "pages" ADD COLUMN "training_leads_content_number_header" varchar DEFAULT 'No.';
  ALTER TABLE "pages" ADD COLUMN "training_leads_content_name_header" varchar DEFAULT 'Name';
  ALTER TABLE "pages" ADD COLUMN "training_leads_content_organization_header" varchar DEFAULT 'Organization';
  ALTER TABLE "pages" ADD COLUMN "training_leads_content_specialisation_header" varchar DEFAULT 'Specialisation';
  ALTER TABLE "pages" ADD COLUMN "training_leads_content_leads_count_label" varchar DEFAULT 'Leads';
  ALTER TABLE "pages" ADD COLUMN "training_leads_content_specialisations_count_label" varchar DEFAULT 'Specialisations';
  ALTER TABLE "pages" ADD COLUMN "training_leads_content_last_updated" varchar DEFAULT 'Updated April 2026';
  ALTER TABLE "pages" ADD COLUMN "nodal_officers_content_nodal_officer_label" varchar DEFAULT 'Nodal Officer';
  ALTER TABLE "pages" ADD COLUMN "nodal_officers_content_fallback_designation" varchar DEFAULT 'Principal Officer';
  ALTER TABLE "pages" ADD COLUMN "nodal_officers_content_sectors_count_label" varchar DEFAULT 'Sectors';
  ALTER TABLE "pages" ADD COLUMN "nodal_officers_content_officers_count_label" varchar DEFAULT 'Officers';
  ALTER TABLE "pages" ADD COLUMN "nodal_officers_content_last_updated" varchar DEFAULT 'Updated April 2026';
  ALTER TABLE "pages" ADD COLUMN "updates_u_i_no_results_message" varchar DEFAULT 'No circulars match your selected filters.';
  ALTER TABLE "pages" ADD COLUMN "updates_u_i_empty_message" varchar DEFAULT 'No regulatory updates available at this time.';
  ALTER TABLE "pages" ADD COLUMN "updates_u_i_view_circular_label" varchar DEFAULT 'View Circular';
  ALTER TABLE "_pages_v_blocks_regulatory_dashboard" ADD COLUMN "view_circular_label" varchar DEFAULT 'View Circular';
  ALTER TABLE "_pages_v_blocks_featured_programs" ADD COLUMN "course_details_label" varchar DEFAULT 'Course Details';
  ALTER TABLE "_pages_v" ADD COLUMN "version_membership_sections_benefits_eyebrow" varchar DEFAULT 'What ARIFAC Engagement Enables';
  ALTER TABLE "_pages_v" ADD COLUMN "version_membership_sections_benefits_heading" varchar DEFAULT 'Capacity building and collaboration benefits for the financial intelligence ecosystem.';
  ALTER TABLE "_pages_v" ADD COLUMN "version_membership_sections_benefits_description" varchar DEFAULT 'Benefits differ by engagement tier, with enhanced access for Members.';
  ALTER TABLE "_pages_v" ADD COLUMN "version_membership_sections_responsibilities_eyebrow" varchar DEFAULT 'Obligations';
  ALTER TABLE "_pages_v" ADD COLUMN "version_membership_sections_responsibilities_heading" varchar DEFAULT 'Member / Affiliate Responsibilities';
  ALTER TABLE "_pages_v" ADD COLUMN "version_membership_sections_responsibilities_description" varchar DEFAULT 'Members are expected to maintain the highest standards of integrity, professionalism, and compliance.';
  ALTER TABLE "_pages_v" ADD COLUMN "version_membership_sections_responsibilities_disclaimer" varchar DEFAULT 'Members must not disclose sensitive regulatory or transaction-related information, including Suspicious Transaction Reporting (STR)-related discussions or any confidential compliance data.';
  ALTER TABLE "_pages_v" ADD COLUMN "version_membership_sections_validity_eyebrow" varchar DEFAULT 'Terms';
  ALTER TABLE "_pages_v" ADD COLUMN "version_membership_sections_validity_heading" varchar DEFAULT 'Validity & Renewal';
  ALTER TABLE "_pages_v" ADD COLUMN "version_membership_sections_fees_eyebrow" varchar DEFAULT 'Pricing';
  ALTER TABLE "_pages_v" ADD COLUMN "version_membership_sections_fees_heading" varchar DEFAULT 'Fees';
  ALTER TABLE "_pages_v" ADD COLUMN "version_membership_sections_fees_description" varchar DEFAULT 'Membership fees are determined by your organisation''s self-declared annual turnover or Assets Under Management (AUM), as applicable. All fees are exclusive of taxes and subject to revision.';
  ALTER TABLE "_pages_v" ADD COLUMN "version_membership_sections_turnover_label" varchar DEFAULT 'Turnover-Based';
  ALTER TABLE "_pages_v" ADD COLUMN "version_membership_sections_aum_label" varchar DEFAULT 'AUM-Based';
  ALTER TABLE "_pages_v" ADD COLUMN "version_membership_sections_fee_suffix" varchar DEFAULT '+ taxes';
  ALTER TABLE "_pages_v" ADD COLUMN "version_membership_sections_turnover_column_header" varchar DEFAULT 'Turnover ₹';
  ALTER TABLE "_pages_v" ADD COLUMN "version_membership_sections_aum_column_header" varchar DEFAULT 'AUM ₹';
  ALTER TABLE "_pages_v" ADD COLUMN "version_membership_sections_fee_column_header" varchar DEFAULT 'Annual Fee';
  ALTER TABLE "_pages_v" ADD COLUMN "version_learners_section_access_eyebrow" varchar DEFAULT 'Access';
  ALTER TABLE "_pages_v" ADD COLUMN "version_learners_section_access_heading" varchar DEFAULT 'Building a foundation for you to learn, engage, and grow';
  ALTER TABLE "_pages_v" ADD COLUMN "version_learners_section_access_description" varchar DEFAULT 'Via access to:';
  ALTER TABLE "_pages_v" ADD COLUMN "version_learners_section_cta_eyebrow" varchar DEFAULT 'Open & Free';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_personal_info_header" varchar DEFAULT 'Personal Information';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_contact_details_header" varchar DEFAULT 'Contact Details';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_professional_bg_header" varchar DEFAULT 'Professional Background';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_expertise_header" varchar DEFAULT 'Area of Expertise';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_expertise_instruction" varchar DEFAULT 'Select all that apply';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_contribution_header" varchar DEFAULT 'How You Can Contribute';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_contribution_label" varchar DEFAULT 'Tell us how you would like to contribute to ARIFAC';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_contribution_placeholder" varchar DEFAULT 'E.g. training delivery, content authoring, research, speaking at events, policy consultation...';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_linkedin_label" varchar DEFAULT 'LinkedIn Profile';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_linkedin_placeholder" varchar DEFAULT 'https://linkedin.com/in/...';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_submit_label" varchar DEFAULT 'Submit Application';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_success_heading" varchar DEFAULT 'Thank you for your interest';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_success_eyebrow" varchar DEFAULT 'Submitted';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_success_description" varchar DEFAULT 'We have received your application. Our team will review your profile and get back to you shortly.';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_why_contribute_header" varchar DEFAULT 'Why Contribute';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_first_name_label" varchar DEFAULT 'First Name';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_last_name_label" varchar DEFAULT 'Last Name';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_email_label" varchar DEFAULT 'Email Address';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_phone_label" varchar DEFAULT 'Phone Number';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_organisation_label" varchar DEFAULT 'Organisation';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_designation_label" varchar DEFAULT 'Designation';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contributor_form_labels_experience_label" varchar DEFAULT 'Years of Experience';
  ALTER TABLE "_pages_v" ADD COLUMN "version_certifications_u_i_filter_title" varchar DEFAULT 'Filter Programmes';
  ALTER TABLE "_pages_v" ADD COLUMN "version_certifications_u_i_search_label" varchar DEFAULT 'Search';
  ALTER TABLE "_pages_v" ADD COLUMN "version_certifications_u_i_search_placeholder" varchar DEFAULT 'Title, focus, topic...';
  ALTER TABLE "_pages_v" ADD COLUMN "version_certifications_u_i_level_label" varchar DEFAULT 'Level';
  ALTER TABLE "_pages_v" ADD COLUMN "version_certifications_u_i_format_label" varchar DEFAULT 'Format';
  ALTER TABLE "_pages_v" ADD COLUMN "version_certifications_u_i_clear_filters_label" varchar DEFAULT 'Clear Filters';
  ALTER TABLE "_pages_v" ADD COLUMN "version_certifications_u_i_curriculum_label" varchar DEFAULT 'Curriculum';
  ALTER TABLE "_pages_v" ADD COLUMN "version_certifications_u_i_live_label" varchar DEFAULT 'Live';
  ALTER TABLE "_pages_v" ADD COLUMN "version_certifications_u_i_live_description" varchar DEFAULT 'This course is now live for employees of reporting entities, based on nominations received from their respective organisations.';
  ALTER TABLE "_pages_v" ADD COLUMN "version_certifications_u_i_coming_soon_label" varchar DEFAULT 'Coming Soon';
  ALTER TABLE "_pages_v" ADD COLUMN "version_certifications_u_i_no_results_message" varchar DEFAULT 'No courses match the selected filters. Try adjusting your search or filter selections.';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contact_form_labels_success_message" varchar DEFAULT 'Thank you! Your message has been sent successfully. We will get back to you shortly.';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contact_form_labels_error_message" varchar DEFAULT 'Oops! Something went wrong. Please try again later.';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contact_form_labels_name_label" varchar DEFAULT 'Full Name';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contact_form_labels_name_placeholder" varchar DEFAULT 'Enter your full name';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contact_form_labels_email_label" varchar DEFAULT 'Email Address';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contact_form_labels_email_placeholder" varchar DEFAULT 'Enter your email address';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contact_form_labels_phone_label" varchar DEFAULT 'Phone Number';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contact_form_labels_phone_placeholder" varchar DEFAULT 'Enter your phone number';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contact_form_labels_subject_label" varchar DEFAULT 'Subject';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contact_form_labels_subject_placeholder" varchar DEFAULT 'How can we help?';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contact_form_labels_message_label" varchar DEFAULT 'Message';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contact_form_labels_message_placeholder" varchar DEFAULT 'Write your message here...';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contact_form_labels_submit_label" varchar DEFAULT 'Send Message';
  ALTER TABLE "_pages_v" ADD COLUMN "version_contact_form_labels_submitting_label" varchar DEFAULT 'Sending...';
  ALTER TABLE "_pages_v" ADD COLUMN "version_members_labels_directory_eyebrow" varchar DEFAULT 'Member Directory';
  ALTER TABLE "_pages_v" ADD COLUMN "version_members_labels_count_label" varchar DEFAULT 'Organisations';
  ALTER TABLE "_pages_v" ADD COLUMN "version_members_labels_footer_label" varchar DEFAULT 'Member Organisations';
  ALTER TABLE "_pages_v" ADD COLUMN "version_training_leads_content_section_eyebrow" varchar DEFAULT 'Expert Network';
  ALTER TABLE "_pages_v" ADD COLUMN "version_training_leads_content_section_heading" varchar DEFAULT 'ARIFAC Training Lead Directory';
  ALTER TABLE "_pages_v" ADD COLUMN "version_training_leads_content_section_description" varchar DEFAULT 'Domain specialists appointed across India''s financial ecosystem to lead certification, capacity building, and AML/CFT training initiatives.';
  ALTER TABLE "_pages_v" ADD COLUMN "version_training_leads_content_number_header" varchar DEFAULT 'No.';
  ALTER TABLE "_pages_v" ADD COLUMN "version_training_leads_content_name_header" varchar DEFAULT 'Name';
  ALTER TABLE "_pages_v" ADD COLUMN "version_training_leads_content_organization_header" varchar DEFAULT 'Organization';
  ALTER TABLE "_pages_v" ADD COLUMN "version_training_leads_content_specialisation_header" varchar DEFAULT 'Specialisation';
  ALTER TABLE "_pages_v" ADD COLUMN "version_training_leads_content_leads_count_label" varchar DEFAULT 'Leads';
  ALTER TABLE "_pages_v" ADD COLUMN "version_training_leads_content_specialisations_count_label" varchar DEFAULT 'Specialisations';
  ALTER TABLE "_pages_v" ADD COLUMN "version_training_leads_content_last_updated" varchar DEFAULT 'Updated April 2026';
  ALTER TABLE "_pages_v" ADD COLUMN "version_nodal_officers_content_nodal_officer_label" varchar DEFAULT 'Nodal Officer';
  ALTER TABLE "_pages_v" ADD COLUMN "version_nodal_officers_content_fallback_designation" varchar DEFAULT 'Principal Officer';
  ALTER TABLE "_pages_v" ADD COLUMN "version_nodal_officers_content_sectors_count_label" varchar DEFAULT 'Sectors';
  ALTER TABLE "_pages_v" ADD COLUMN "version_nodal_officers_content_officers_count_label" varchar DEFAULT 'Officers';
  ALTER TABLE "_pages_v" ADD COLUMN "version_nodal_officers_content_last_updated" varchar DEFAULT 'Updated April 2026';
  ALTER TABLE "_pages_v" ADD COLUMN "version_updates_u_i_no_results_message" varchar DEFAULT 'No circulars match your selected filters.';
  ALTER TABLE "_pages_v" ADD COLUMN "version_updates_u_i_empty_message" varchar DEFAULT 'No regulatory updates available at this time.';
  ALTER TABLE "_pages_v" ADD COLUMN "version_updates_u_i_view_circular_label" varchar DEFAULT 'View Circular';
  ALTER TABLE "programmes" ADD COLUMN "labels_active_channels_label" varchar DEFAULT 'Active Channels';
  ALTER TABLE "programmes" ADD COLUMN "labels_sessions_label" varchar DEFAULT 'Sessions';
  ALTER TABLE "programmes" ADD COLUMN "labels_institutional_dialogue_eyebrow" varchar DEFAULT 'Institutional Dialogue';
  ALTER TABLE "programmes" ADD COLUMN "labels_annual_meetings_description" varchar DEFAULT 'Structured convergence platforms facilitating knowledge exchange and strategic alignment between ecosystem stakeholders.';
  ALTER TABLE "programmes" ADD COLUMN "labels_programme_table_header" varchar DEFAULT 'Programme';
  ALTER TABLE "programmes" ADD COLUMN "labels_format_table_header" varchar DEFAULT 'Format';
  ALTER TABLE "programmes" ADD COLUMN "labels_timeline_table_header" varchar DEFAULT 'Timeline';
  ALTER TABLE "programmes" ADD COLUMN "labels_year_table_header" varchar DEFAULT 'Year';
  ALTER TABLE "programmes" ADD COLUMN "labels_meeting_table_header" varchar DEFAULT 'Meeting';
  ALTER TABLE "programmes" ADD COLUMN "labels_date_table_header" varchar DEFAULT 'Date';
  ALTER TABLE "programmes" ADD COLUMN "labels_location_table_header" varchar DEFAULT 'Location';
  ALTER TABLE "_programmes_v" ADD COLUMN "version_labels_active_channels_label" varchar DEFAULT 'Active Channels';
  ALTER TABLE "_programmes_v" ADD COLUMN "version_labels_sessions_label" varchar DEFAULT 'Sessions';
  ALTER TABLE "_programmes_v" ADD COLUMN "version_labels_institutional_dialogue_eyebrow" varchar DEFAULT 'Institutional Dialogue';
  ALTER TABLE "_programmes_v" ADD COLUMN "version_labels_annual_meetings_description" varchar DEFAULT 'Structured convergence platforms facilitating knowledge exchange and strategic alignment between ecosystem stakeholders.';
  ALTER TABLE "_programmes_v" ADD COLUMN "version_labels_programme_table_header" varchar DEFAULT 'Programme';
  ALTER TABLE "_programmes_v" ADD COLUMN "version_labels_format_table_header" varchar DEFAULT 'Format';
  ALTER TABLE "_programmes_v" ADD COLUMN "version_labels_timeline_table_header" varchar DEFAULT 'Timeline';
  ALTER TABLE "_programmes_v" ADD COLUMN "version_labels_year_table_header" varchar DEFAULT 'Year';
  ALTER TABLE "_programmes_v" ADD COLUMN "version_labels_meeting_table_header" varchar DEFAULT 'Meeting';
  ALTER TABLE "_programmes_v" ADD COLUMN "version_labels_date_table_header" varchar DEFAULT 'Date';
  ALTER TABLE "_programmes_v" ADD COLUMN "version_labels_location_table_header" varchar DEFAULT 'Location';
  ALTER TABLE "header" ADD COLUMN "login_label" varchar DEFAULT 'Login';
  ALTER TABLE "header" ADD COLUMN "login_as_label" varchar DEFAULT 'Login As';
  ALTER TABLE "header" ADD COLUMN "organization_login_label" varchar DEFAULT 'Organization';
  ALTER TABLE "header" ADD COLUMN "organization_login_description" varchar DEFAULT 'Member portal access';
  ALTER TABLE "header" ADD COLUMN "learner_login_label" varchar DEFAULT 'Learner';
  ALTER TABLE "header" ADD COLUMN "learner_login_description" varchar DEFAULT 'Learning platform access';
  ALTER TABLE "pages_contributor_form_labels_experience_options" ADD CONSTRAINT "pages_contributor_form_labels_experience_options_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_pages_v_version_contributor_form_labels_experience_options" ADD CONSTRAINT "_pages_v_version_contributor_form_labels_experience_options_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "site_settings_category_labels" ADD CONSTRAINT "site_settings_category_labels_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."site_settings"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "site_settings_issuing_body_labels" ADD CONSTRAINT "site_settings_issuing_body_labels_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."site_settings"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "pages_contributor_form_labels_experience_options_order_idx" ON "pages_contributor_form_labels_experience_options" USING btree ("_order");
  CREATE INDEX "pages_contributor_form_labels_experience_options_parent_id_idx" ON "pages_contributor_form_labels_experience_options" USING btree ("_parent_id");
  CREATE INDEX "_pages_v_version_contributor_form_labels_experience_options_order_idx" ON "_pages_v_version_contributor_form_labels_experience_options" USING btree ("_order");
  CREATE INDEX "_pages_v_version_contributor_form_labels_experience_options_parent_id_idx" ON "_pages_v_version_contributor_form_labels_experience_options" USING btree ("_parent_id");
  CREATE INDEX "site_settings_category_labels_order_idx" ON "site_settings_category_labels" USING btree ("_order");
  CREATE INDEX "site_settings_category_labels_parent_id_idx" ON "site_settings_category_labels" USING btree ("_parent_id");
  CREATE INDEX "site_settings_issuing_body_labels_order_idx" ON "site_settings_issuing_body_labels" USING btree ("_order");
  CREATE INDEX "site_settings_issuing_body_labels_parent_id_idx" ON "site_settings_issuing_body_labels" USING btree ("_parent_id");
  `)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_contributor_form_labels_experience_options" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_version_contributor_form_labels_experience_options" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "site_settings_category_labels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "site_settings_issuing_body_labels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "site_settings" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "pages_contributor_form_labels_experience_options" CASCADE;
  DROP TABLE "_pages_v_version_contributor_form_labels_experience_options" CASCADE;
  DROP TABLE "site_settings_category_labels" CASCADE;
  DROP TABLE "site_settings_issuing_body_labels" CASCADE;
  DROP TABLE "site_settings" CASCADE;
  ALTER TABLE "pages" ALTER COLUMN "page_type" SET DATA TYPE text;
  ALTER TABLE "pages" ALTER COLUMN "page_type" SET DEFAULT 'simple'::text;
  DROP TYPE "public"."enum_pages_page_type";
  CREATE TYPE "public"."enum_pages_page_type" AS ENUM('simple', 'home', 'about', 'contact', 'membership', 'learners', 'contributor', 'certifications', 'updates');
  ALTER TABLE "pages" ALTER COLUMN "page_type" SET DEFAULT 'simple'::"public"."enum_pages_page_type";
  ALTER TABLE "pages" ALTER COLUMN "page_type" SET DATA TYPE "public"."enum_pages_page_type" USING "page_type"::"public"."enum_pages_page_type";
  ALTER TABLE "_pages_v" ALTER COLUMN "version_page_type" SET DATA TYPE text;
  ALTER TABLE "_pages_v" ALTER COLUMN "version_page_type" SET DEFAULT 'simple'::text;
  DROP TYPE "public"."enum__pages_v_version_page_type";
  CREATE TYPE "public"."enum__pages_v_version_page_type" AS ENUM('simple', 'home', 'about', 'contact', 'membership', 'learners', 'contributor', 'certifications', 'updates');
  ALTER TABLE "_pages_v" ALTER COLUMN "version_page_type" SET DEFAULT 'simple'::"public"."enum__pages_v_version_page_type";
  ALTER TABLE "_pages_v" ALTER COLUMN "version_page_type" SET DATA TYPE "public"."enum__pages_v_version_page_type" USING "version_page_type"::"public"."enum__pages_v_version_page_type";
  ALTER TABLE "pages_blocks_regulatory_dashboard" DROP COLUMN "view_circular_label";
  ALTER TABLE "pages_blocks_featured_programs" DROP COLUMN "course_details_label";
  ALTER TABLE "pages" DROP COLUMN "membership_sections_benefits_eyebrow";
  ALTER TABLE "pages" DROP COLUMN "membership_sections_benefits_heading";
  ALTER TABLE "pages" DROP COLUMN "membership_sections_benefits_description";
  ALTER TABLE "pages" DROP COLUMN "membership_sections_responsibilities_eyebrow";
  ALTER TABLE "pages" DROP COLUMN "membership_sections_responsibilities_heading";
  ALTER TABLE "pages" DROP COLUMN "membership_sections_responsibilities_description";
  ALTER TABLE "pages" DROP COLUMN "membership_sections_responsibilities_disclaimer";
  ALTER TABLE "pages" DROP COLUMN "membership_sections_validity_eyebrow";
  ALTER TABLE "pages" DROP COLUMN "membership_sections_validity_heading";
  ALTER TABLE "pages" DROP COLUMN "membership_sections_fees_eyebrow";
  ALTER TABLE "pages" DROP COLUMN "membership_sections_fees_heading";
  ALTER TABLE "pages" DROP COLUMN "membership_sections_fees_description";
  ALTER TABLE "pages" DROP COLUMN "membership_sections_turnover_label";
  ALTER TABLE "pages" DROP COLUMN "membership_sections_aum_label";
  ALTER TABLE "pages" DROP COLUMN "membership_sections_fee_suffix";
  ALTER TABLE "pages" DROP COLUMN "membership_sections_turnover_column_header";
  ALTER TABLE "pages" DROP COLUMN "membership_sections_aum_column_header";
  ALTER TABLE "pages" DROP COLUMN "membership_sections_fee_column_header";
  ALTER TABLE "pages" DROP COLUMN "learners_section_access_eyebrow";
  ALTER TABLE "pages" DROP COLUMN "learners_section_access_heading";
  ALTER TABLE "pages" DROP COLUMN "learners_section_access_description";
  ALTER TABLE "pages" DROP COLUMN "learners_section_cta_eyebrow";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_personal_info_header";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_contact_details_header";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_professional_bg_header";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_expertise_header";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_expertise_instruction";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_contribution_header";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_contribution_label";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_contribution_placeholder";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_linkedin_label";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_linkedin_placeholder";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_submit_label";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_success_heading";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_success_eyebrow";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_success_description";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_why_contribute_header";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_first_name_label";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_last_name_label";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_email_label";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_phone_label";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_organisation_label";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_designation_label";
  ALTER TABLE "pages" DROP COLUMN "contributor_form_labels_experience_label";
  ALTER TABLE "pages" DROP COLUMN "certifications_u_i_filter_title";
  ALTER TABLE "pages" DROP COLUMN "certifications_u_i_search_label";
  ALTER TABLE "pages" DROP COLUMN "certifications_u_i_search_placeholder";
  ALTER TABLE "pages" DROP COLUMN "certifications_u_i_level_label";
  ALTER TABLE "pages" DROP COLUMN "certifications_u_i_format_label";
  ALTER TABLE "pages" DROP COLUMN "certifications_u_i_clear_filters_label";
  ALTER TABLE "pages" DROP COLUMN "certifications_u_i_curriculum_label";
  ALTER TABLE "pages" DROP COLUMN "certifications_u_i_live_label";
  ALTER TABLE "pages" DROP COLUMN "certifications_u_i_live_description";
  ALTER TABLE "pages" DROP COLUMN "certifications_u_i_coming_soon_label";
  ALTER TABLE "pages" DROP COLUMN "certifications_u_i_no_results_message";
  ALTER TABLE "pages" DROP COLUMN "contact_form_labels_success_message";
  ALTER TABLE "pages" DROP COLUMN "contact_form_labels_error_message";
  ALTER TABLE "pages" DROP COLUMN "contact_form_labels_name_label";
  ALTER TABLE "pages" DROP COLUMN "contact_form_labels_name_placeholder";
  ALTER TABLE "pages" DROP COLUMN "contact_form_labels_email_label";
  ALTER TABLE "pages" DROP COLUMN "contact_form_labels_email_placeholder";
  ALTER TABLE "pages" DROP COLUMN "contact_form_labels_phone_label";
  ALTER TABLE "pages" DROP COLUMN "contact_form_labels_phone_placeholder";
  ALTER TABLE "pages" DROP COLUMN "contact_form_labels_subject_label";
  ALTER TABLE "pages" DROP COLUMN "contact_form_labels_subject_placeholder";
  ALTER TABLE "pages" DROP COLUMN "contact_form_labels_message_label";
  ALTER TABLE "pages" DROP COLUMN "contact_form_labels_message_placeholder";
  ALTER TABLE "pages" DROP COLUMN "contact_form_labels_submit_label";
  ALTER TABLE "pages" DROP COLUMN "contact_form_labels_submitting_label";
  ALTER TABLE "pages" DROP COLUMN "members_labels_directory_eyebrow";
  ALTER TABLE "pages" DROP COLUMN "members_labels_count_label";
  ALTER TABLE "pages" DROP COLUMN "members_labels_footer_label";
  ALTER TABLE "pages" DROP COLUMN "training_leads_content_section_eyebrow";
  ALTER TABLE "pages" DROP COLUMN "training_leads_content_section_heading";
  ALTER TABLE "pages" DROP COLUMN "training_leads_content_section_description";
  ALTER TABLE "pages" DROP COLUMN "training_leads_content_number_header";
  ALTER TABLE "pages" DROP COLUMN "training_leads_content_name_header";
  ALTER TABLE "pages" DROP COLUMN "training_leads_content_organization_header";
  ALTER TABLE "pages" DROP COLUMN "training_leads_content_specialisation_header";
  ALTER TABLE "pages" DROP COLUMN "training_leads_content_leads_count_label";
  ALTER TABLE "pages" DROP COLUMN "training_leads_content_specialisations_count_label";
  ALTER TABLE "pages" DROP COLUMN "training_leads_content_last_updated";
  ALTER TABLE "pages" DROP COLUMN "nodal_officers_content_nodal_officer_label";
  ALTER TABLE "pages" DROP COLUMN "nodal_officers_content_fallback_designation";
  ALTER TABLE "pages" DROP COLUMN "nodal_officers_content_sectors_count_label";
  ALTER TABLE "pages" DROP COLUMN "nodal_officers_content_officers_count_label";
  ALTER TABLE "pages" DROP COLUMN "nodal_officers_content_last_updated";
  ALTER TABLE "pages" DROP COLUMN "updates_u_i_no_results_message";
  ALTER TABLE "pages" DROP COLUMN "updates_u_i_empty_message";
  ALTER TABLE "pages" DROP COLUMN "updates_u_i_view_circular_label";
  ALTER TABLE "_pages_v_blocks_regulatory_dashboard" DROP COLUMN "view_circular_label";
  ALTER TABLE "_pages_v_blocks_featured_programs" DROP COLUMN "course_details_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_membership_sections_benefits_eyebrow";
  ALTER TABLE "_pages_v" DROP COLUMN "version_membership_sections_benefits_heading";
  ALTER TABLE "_pages_v" DROP COLUMN "version_membership_sections_benefits_description";
  ALTER TABLE "_pages_v" DROP COLUMN "version_membership_sections_responsibilities_eyebrow";
  ALTER TABLE "_pages_v" DROP COLUMN "version_membership_sections_responsibilities_heading";
  ALTER TABLE "_pages_v" DROP COLUMN "version_membership_sections_responsibilities_description";
  ALTER TABLE "_pages_v" DROP COLUMN "version_membership_sections_responsibilities_disclaimer";
  ALTER TABLE "_pages_v" DROP COLUMN "version_membership_sections_validity_eyebrow";
  ALTER TABLE "_pages_v" DROP COLUMN "version_membership_sections_validity_heading";
  ALTER TABLE "_pages_v" DROP COLUMN "version_membership_sections_fees_eyebrow";
  ALTER TABLE "_pages_v" DROP COLUMN "version_membership_sections_fees_heading";
  ALTER TABLE "_pages_v" DROP COLUMN "version_membership_sections_fees_description";
  ALTER TABLE "_pages_v" DROP COLUMN "version_membership_sections_turnover_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_membership_sections_aum_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_membership_sections_fee_suffix";
  ALTER TABLE "_pages_v" DROP COLUMN "version_membership_sections_turnover_column_header";
  ALTER TABLE "_pages_v" DROP COLUMN "version_membership_sections_aum_column_header";
  ALTER TABLE "_pages_v" DROP COLUMN "version_membership_sections_fee_column_header";
  ALTER TABLE "_pages_v" DROP COLUMN "version_learners_section_access_eyebrow";
  ALTER TABLE "_pages_v" DROP COLUMN "version_learners_section_access_heading";
  ALTER TABLE "_pages_v" DROP COLUMN "version_learners_section_access_description";
  ALTER TABLE "_pages_v" DROP COLUMN "version_learners_section_cta_eyebrow";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_personal_info_header";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_contact_details_header";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_professional_bg_header";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_expertise_header";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_expertise_instruction";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_contribution_header";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_contribution_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_contribution_placeholder";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_linkedin_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_linkedin_placeholder";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_submit_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_success_heading";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_success_eyebrow";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_success_description";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_why_contribute_header";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_first_name_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_last_name_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_email_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_phone_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_organisation_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_designation_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contributor_form_labels_experience_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_certifications_u_i_filter_title";
  ALTER TABLE "_pages_v" DROP COLUMN "version_certifications_u_i_search_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_certifications_u_i_search_placeholder";
  ALTER TABLE "_pages_v" DROP COLUMN "version_certifications_u_i_level_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_certifications_u_i_format_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_certifications_u_i_clear_filters_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_certifications_u_i_curriculum_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_certifications_u_i_live_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_certifications_u_i_live_description";
  ALTER TABLE "_pages_v" DROP COLUMN "version_certifications_u_i_coming_soon_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_certifications_u_i_no_results_message";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contact_form_labels_success_message";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contact_form_labels_error_message";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contact_form_labels_name_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contact_form_labels_name_placeholder";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contact_form_labels_email_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contact_form_labels_email_placeholder";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contact_form_labels_phone_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contact_form_labels_phone_placeholder";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contact_form_labels_subject_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contact_form_labels_subject_placeholder";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contact_form_labels_message_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contact_form_labels_message_placeholder";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contact_form_labels_submit_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_contact_form_labels_submitting_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_members_labels_directory_eyebrow";
  ALTER TABLE "_pages_v" DROP COLUMN "version_members_labels_count_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_members_labels_footer_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_training_leads_content_section_eyebrow";
  ALTER TABLE "_pages_v" DROP COLUMN "version_training_leads_content_section_heading";
  ALTER TABLE "_pages_v" DROP COLUMN "version_training_leads_content_section_description";
  ALTER TABLE "_pages_v" DROP COLUMN "version_training_leads_content_number_header";
  ALTER TABLE "_pages_v" DROP COLUMN "version_training_leads_content_name_header";
  ALTER TABLE "_pages_v" DROP COLUMN "version_training_leads_content_organization_header";
  ALTER TABLE "_pages_v" DROP COLUMN "version_training_leads_content_specialisation_header";
  ALTER TABLE "_pages_v" DROP COLUMN "version_training_leads_content_leads_count_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_training_leads_content_specialisations_count_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_training_leads_content_last_updated";
  ALTER TABLE "_pages_v" DROP COLUMN "version_nodal_officers_content_nodal_officer_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_nodal_officers_content_fallback_designation";
  ALTER TABLE "_pages_v" DROP COLUMN "version_nodal_officers_content_sectors_count_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_nodal_officers_content_officers_count_label";
  ALTER TABLE "_pages_v" DROP COLUMN "version_nodal_officers_content_last_updated";
  ALTER TABLE "_pages_v" DROP COLUMN "version_updates_u_i_no_results_message";
  ALTER TABLE "_pages_v" DROP COLUMN "version_updates_u_i_empty_message";
  ALTER TABLE "_pages_v" DROP COLUMN "version_updates_u_i_view_circular_label";
  ALTER TABLE "programmes" DROP COLUMN "labels_active_channels_label";
  ALTER TABLE "programmes" DROP COLUMN "labels_sessions_label";
  ALTER TABLE "programmes" DROP COLUMN "labels_institutional_dialogue_eyebrow";
  ALTER TABLE "programmes" DROP COLUMN "labels_annual_meetings_description";
  ALTER TABLE "programmes" DROP COLUMN "labels_programme_table_header";
  ALTER TABLE "programmes" DROP COLUMN "labels_format_table_header";
  ALTER TABLE "programmes" DROP COLUMN "labels_timeline_table_header";
  ALTER TABLE "programmes" DROP COLUMN "labels_year_table_header";
  ALTER TABLE "programmes" DROP COLUMN "labels_meeting_table_header";
  ALTER TABLE "programmes" DROP COLUMN "labels_date_table_header";
  ALTER TABLE "programmes" DROP COLUMN "labels_location_table_header";
  ALTER TABLE "_programmes_v" DROP COLUMN "version_labels_active_channels_label";
  ALTER TABLE "_programmes_v" DROP COLUMN "version_labels_sessions_label";
  ALTER TABLE "_programmes_v" DROP COLUMN "version_labels_institutional_dialogue_eyebrow";
  ALTER TABLE "_programmes_v" DROP COLUMN "version_labels_annual_meetings_description";
  ALTER TABLE "_programmes_v" DROP COLUMN "version_labels_programme_table_header";
  ALTER TABLE "_programmes_v" DROP COLUMN "version_labels_format_table_header";
  ALTER TABLE "_programmes_v" DROP COLUMN "version_labels_timeline_table_header";
  ALTER TABLE "_programmes_v" DROP COLUMN "version_labels_year_table_header";
  ALTER TABLE "_programmes_v" DROP COLUMN "version_labels_meeting_table_header";
  ALTER TABLE "_programmes_v" DROP COLUMN "version_labels_date_table_header";
  ALTER TABLE "_programmes_v" DROP COLUMN "version_labels_location_table_header";
  ALTER TABLE "header" DROP COLUMN "login_label";
  ALTER TABLE "header" DROP COLUMN "login_as_label";
  ALTER TABLE "header" DROP COLUMN "organization_login_label";
  ALTER TABLE "header" DROP COLUMN "organization_login_description";
  ALTER TABLE "header" DROP COLUMN "learner_login_label";
  ALTER TABLE "header" DROP COLUMN "learner_login_description";`)
}
