/* tslint:disable */
/* eslint-disable */
/**
 * This file was originally intended to be auto-generated by Payload.
 * Hand-written to match collection/global/block schemas due to Payload CLI
 * incompatibility with Node.js 25 ESM resolution.
 * Regenerate with: npx payload generate:types
 */

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  collections: {
    users: User
    pages: Page
    'regulatory-updates': RegulatoryUpdate
    certifications: Certification
    'news-items': NewsItem
  }
  collectionsJoins: Record<string, never>
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    pages: PagesSelect<false> | PagesSelect<true>
    'regulatory-updates': RegulatoryUpdatesSelect<false> | RegulatoryUpdatesSelect<true>
    certifications: CertificationsSelect<false> | CertificationsSelect<true>
    'news-items': NewsItemsSelect<false> | NewsItemsSelect<true>
  }
  db: {
    defaultIDType: number
  }
  globals: {
    programmes: Programme
  }
  globalsSelect: {
    programmes: ProgrammesSelect<false> | ProgrammesSelect<true>
  }
  locale: null
  user: User & {
    collection: 'users'
  }
}

export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}

/**
 * Users collection
 */
export interface User {
  id: number
  name: string
  role: 'admin' | 'editor'
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  password?: string | null
}

/**
 * Pages collection
 */
export interface Page {
  id: number
  title: string
  slug: string
  pageType: 'simple' | 'home' | 'about' | 'contact'
  banner?: {
    label?: string | null
    title?: string | null
    description?: string | null
  }
  body?: Record<string, unknown>[] | null
  layout?: (HeroBlock | StatsBlock | CapabilityMatrixBlock | RegulatoryDashboardBlock | FeaturedProgramsBlock | CTABlock)[] | null
  updatedAt: string
  createdAt: string
  _status?: string | null
}

/**
 * Hero block
 */
export interface HeroBlock {
  blockType: 'hero'
  id?: string | null
  tagline: string
  heading: string
  headingHighlight?: string | null
  headingTrail?: string | null
  description: string
  primaryButton?: {
    label: string
    link: string
  }
  secondaryButton?: {
    label: string
    link: string
  }
  sideCard?: {
    strategicAlignmentText?: string | null
    industryLedText?: string | null
  }
}

/**
 * Stats block
 */
export interface StatsBlock {
  blockType: 'stats'
  id?: string | null
  stats: {
    label: string
    value: string
    id?: string | null
  }[]
}

/**
 * Capability Matrix block
 */
export interface CapabilityMatrixBlock {
  blockType: 'capabilityMatrix'
  id?: string | null
  sectionHeading: string
  sectionHeadingHighlight?: string | null
  sectionDescription?: string | null
  mandates: {
    label: string
    title: string
    description: string
    linkText: string
    linkRef: string
    id?: string | null
  }[]
}

/**
 * Regulatory Dashboard block
 */
export interface RegulatoryDashboardBlock {
  blockType: 'regulatoryDashboard'
  id?: string | null
  sectionEyebrow?: string | null
  sectionHeading: string
  sectionDescription?: string | null
  ctaText?: string | null
  ctaLink?: string | null
}

/**
 * Featured Programs block
 */
export interface FeaturedProgramsBlock {
  blockType: 'featuredPrograms'
  id?: string | null
  sectionEyebrow?: string | null
  sectionHeading: string
  sectionDescription?: string | null
  viewAllText?: string | null
  viewAllLink?: string | null
  programs: {
    title: string
    category: string
    description: string
    link: string
    image?: string | null
    id?: string | null
  }[]
}

/**
 * CTA block
 */
export interface CTABlock {
  blockType: 'cta'
  id?: string | null
  heading: string
  description: string
  primaryButton?: {
    label: string
    link: string
  }
  secondaryButton?: {
    label?: string | null
    link?: string | null
  }
}

/**
 * Regulatory Updates collection
 */
export interface RegulatoryUpdate {
  id: number
  title: string
  date: string
  referenceNumber: string
  category: 'aml-cft' | 'kyc-cdd' | 'reporting' | 'digital-onboarding' | 'fraud-cyber' | 'sanctions' | 'compliance-governance'
  issuingBody: 'rbi' | 'fiu-ind' | 'sebi' | 'irdai'
  link?: string | null
  updatedAt: string
  createdAt: string
  _status?: string | null
}

/**
 * Certifications collection
 */
export interface Certification {
  id: number
  title: string
  level: string
  focus: string
  category: 'Foundation' | 'Professional' | 'Specialist' | 'Strategic'
  format: string
  description: string
  curriculum?: {
    item: string
    id?: string | null
  }[] | null
  duration: string
  updatedAt: string
  createdAt: string
  _status?: string | null
}

/**
 * News Items collection
 */
export interface NewsItem {
  id: number
  text: string
  published: boolean
  updatedAt: string
  createdAt: string
  _status?: string | null
}

/**
 * Programmes global
 */
export interface Programme {
  id: number
  engagementFormats?: {
    title: string
    description: string
    points?: {
      text?: string | null
      id?: string | null
    }[] | null
    id?: string | null
  }[] | null
  programmeSchedule?: {
    name: string
    type: string
    date: string
    id?: string | null
  }[] | null
  annualMeetings?: {
    name: string
    date: string
    location: string
    id?: string | null
  }[] | null
  updatedAt?: string | null
  createdAt?: string | null
  globalType?: string | null
}

/**
 * Select types for collections
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T
  role?: T
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
  password?: T
}

export interface PagesSelect<T extends boolean = true> {
  title?: T
  slug?: T
  pageType?: T
  banner?:
    | T
    | {
        label?: T
        title?: T
        description?: T
      }
  body?: T
  layout?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}

export interface RegulatoryUpdatesSelect<T extends boolean = true> {
  title?: T
  date?: T
  referenceNumber?: T
  category?: T
  issuingBody?: T
  link?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}

export interface CertificationsSelect<T extends boolean = true> {
  title?: T
  level?: T
  focus?: T
  category?: T
  format?: T
  description?: T
  curriculum?: T
  duration?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}

export interface NewsItemsSelect<T extends boolean = true> {
  text?: T
  published?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}

export interface ProgrammesSelect<T extends boolean = true> {
  engagementFormats?: T
  programmeSchedule?: T
  annualMeetings?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
