/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    media: Media;
    'regulatory-updates': RegulatoryUpdate;
    certifications: Certification;
    'news-items': NewsItem;
    members: Member;
    'legal-pages': LegalPage;
    'nodal-officers': NodalOfficer;
    'training-leads-directory': TrainingLeadsDirectory;
    'gallery-items': GalleryItem;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'regulatory-updates': RegulatoryUpdatesSelect<false> | RegulatoryUpdatesSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    'news-items': NewsItemsSelect<false> | NewsItemsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    'nodal-officers': NodalOfficersSelect<false> | NodalOfficersSelect<true>;
    'training-leads-directory': TrainingLeadsDirectorySelect<false> | TrainingLeadsDirectorySelect<true>;
    'gallery-items': GalleryItemsSelect<false> | GalleryItemsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    programmes: Programme;
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    'gallery-page': GalleryPage;
  };
  globalsSelect: {
    programmes: ProgrammesSelect<false> | ProgrammesSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'gallery-page': GalleryPageSelect<false> | GalleryPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  pageType:
    | 'simple'
    | 'home'
    | 'about'
    | 'contact'
    | 'membership'
    | 'learners'
    | 'contributor'
    | 'certifications'
    | 'updates'
    | 'members'
    | 'training-leads'
    | 'nodal-officers';
  banner?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
  };
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  layout?:
    | (
        | {
            tagline: string;
            heading: string;
            headingHighlight?: string | null;
            headingTrail?: string | null;
            description: string;
            primaryButton: {
              label: string;
              link: string;
            };
            secondaryButton: {
              label: string;
              link: string;
            };
            sideCard?: {
              strategicAlignmentText?: string | null;
              industryLedText?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            stats: {
              label: string;
              value: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            sectionHeading: string;
            sectionHeadingHighlight?: string | null;
            sectionDescription?: string | null;
            mandates: {
              label: string;
              title: string;
              description: string;
              linkText: string;
              linkRef: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'capabilityMatrix';
          }
        | {
            sectionEyebrow?: string | null;
            sectionHeading: string;
            sectionDescription?: string | null;
            ctaText?: string | null;
            ctaLink?: string | null;
            viewCircularLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'regulatoryDashboard';
          }
        | {
            sectionEyebrow?: string | null;
            sectionHeading: string;
            sectionDescription?: string | null;
            viewAllText?: string | null;
            viewAllLink?: string | null;
            programs: {
              title: string;
              category: string;
              description: string;
              link: string;
              image?: string | null;
              id?: string | null;
            }[];
            courseDetailsLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredPrograms';
          }
        | {
            heading: string;
            description: string;
            primaryButton: {
              label: string;
              link: string;
            };
            secondaryButton?: {
              label?: string | null;
              link?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            label?: string | null;
            heading: string;
            description?: string | null;
            guidanceCard: {
              label?: string | null;
              title: string;
              logoUrl?: string | null;
            };
            disclaimer?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'partnerships';
          }
      )[]
    | null;
  whySection?: {
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    threats?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    alignedWith?: {
      description?: string | null;
      items?:
        | {
            label: string;
            value: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  whatSection?: {
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    focusAreas?:
      | {
          number: string;
          title: string;
          points?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  whoSection?: {
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaLink?: string | null;
    audiences?:
      | {
          name: string;
          subtitle: string;
          id?: string | null;
        }[]
      | null;
  };
  membershipIntro?: {
    subheading?: string | null;
    description?: string | null;
  };
  benefits?:
    | {
        category: string;
        items?:
          | {
              title: string;
              description: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  responsibilities?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  validityTerms?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  feeTables?: {
    turnoverBased?:
      | {
          tier: string;
          fee: string;
          id?: string | null;
        }[]
      | null;
    aumBased?:
      | {
          tier: string;
          fee: string;
          id?: string | null;
        }[]
      | null;
  };
  membershipCta?: {
    label?: string | null;
    link?: string | null;
  };
  membershipSections?: {
    benefitsEyebrow?: string | null;
    benefitsHeading?: string | null;
    benefitsDescription?: string | null;
    responsibilitiesEyebrow?: string | null;
    responsibilitiesHeading?: string | null;
    responsibilitiesDescription?: string | null;
    responsibilitiesDisclaimer?: string | null;
    validityEyebrow?: string | null;
    validityHeading?: string | null;
    feesEyebrow?: string | null;
    feesHeading?: string | null;
    feesDescription?: string | null;
    feeScheduleLabel?: string | null;
    turnoverLabel?: string | null;
    aumLabel?: string | null;
    feeSuffix?: string | null;
    turnoverColumnHeader?: string | null;
    aumColumnHeader?: string | null;
    feeColumnHeader?: string | null;
  };
  accessItems?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  learnersCta?: {
    heading?: string | null;
    description?: string | null;
    buttonLabel?: string | null;
    buttonLink?: string | null;
  };
  learnersSection?: {
    accessEyebrow?: string | null;
    accessHeading?: string | null;
    accessDescription?: string | null;
    ctaEyebrow?: string | null;
  };
  expertiseAreas?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  whyContribute?: {
    heading?: string | null;
    points?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  contributorFormLabels?: {
    personalInfoHeader?: string | null;
    contactDetailsHeader?: string | null;
    professionalBgHeader?: string | null;
    expertiseHeader?: string | null;
    expertiseInstruction?: string | null;
    contributionHeader?: string | null;
    contributionLabel?: string | null;
    contributionPlaceholder?: string | null;
    linkedinLabel?: string | null;
    linkedinPlaceholder?: string | null;
    submitLabel?: string | null;
    successHeading?: string | null;
    successEyebrow?: string | null;
    successDescription?: string | null;
    whyContributeHeader?: string | null;
    firstNameLabel?: string | null;
    lastNameLabel?: string | null;
    emailLabel?: string | null;
    phoneLabel?: string | null;
    organisationLabel?: string | null;
    designationLabel?: string | null;
    experienceLabel?: string | null;
    experienceOptions?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  pathwayTiers?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  certificationsUI?: {
    filterTitle?: string | null;
    searchLabel?: string | null;
    searchPlaceholder?: string | null;
    levelLabel?: string | null;
    formatLabel?: string | null;
    clearFiltersLabel?: string | null;
    curriculumLabel?: string | null;
    liveLabel?: string | null;
    liveDescription?: string | null;
    comingSoonLabel?: string | null;
    noResultsMessage?: string | null;
  };
  formSection?: {
    eyebrow?: string | null;
    heading?: string | null;
  };
  contactInfo?: {
    eyebrow?: string | null;
    entries?:
      | {
          label: string;
          links?:
            | {
                text: string;
                url: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  contactFormLabels?: {
    successMessage?: string | null;
    errorMessage?: string | null;
    nameLabel?: string | null;
    namePlaceholder?: string | null;
    emailLabel?: string | null;
    emailPlaceholder?: string | null;
    phoneLabel?: string | null;
    phonePlaceholder?: string | null;
    subjectLabel?: string | null;
    subjectPlaceholder?: string | null;
    messageLabel?: string | null;
    messagePlaceholder?: string | null;
    submitLabel?: string | null;
    submittingLabel?: string | null;
  };
  membersLabels?: {
    directoryEyebrow?: string | null;
    countLabel?: string | null;
    footerLabel?: string | null;
  };
  trainingLeadsContent?: {
    sectionEyebrow?: string | null;
    sectionHeading?: string | null;
    sectionDescription?: string | null;
    numberHeader?: string | null;
    nameHeader?: string | null;
    organizationHeader?: string | null;
    specialisationHeader?: string | null;
    leadsCountLabel?: string | null;
    specialisationsCountLabel?: string | null;
    lastUpdated?: string | null;
  };
  nodalOfficersContent?: {
    nodalOfficerLabel?: string | null;
    fallbackDesignation?: string | null;
    sectorsCountLabel?: string | null;
    officersCountLabel?: string | null;
    lastUpdated?: string | null;
  };
  updatesUI?: {
    noResultsMessage?: string | null;
    emptyMessage?: string | null;
    viewCircularLabel?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulatory-updates".
 */
export interface RegulatoryUpdate {
  id: number;
  title: string;
  date: string;
  referenceNumber: string;
  category:
    | 'aml-cft'
    | 'kyc-cdd'
    | 'reporting'
    | 'digital-onboarding'
    | 'fraud-cyber'
    | 'sanctions'
    | 'compliance-governance';
  issuingBody: 'rbi' | 'fiu-ind' | 'sebi' | 'irdai';
  /**
   * Upload a PDF. If set, "View Circular" will open this file. Takes precedence over the link below.
   */
  pdf?: (number | null) | Media;
  /**
   * Optional external URL. Used only when no PDF is uploaded.
   */
  link?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  title: string;
  level: string;
  focus: string;
  category: string;
  format: string;
  description: string;
  curriculum?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  duration: string;
  /**
   * Shown as a badge on the certification card.
   */
  launchStatus: 'live' | 'coming-soon';
  /**
   * Lower numbers appear first on the certifications page.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-items".
 */
export interface NewsItem {
  id: number;
  text: string;
  published: boolean;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  title: string;
  slug: string;
  contactEmail?: string | null;
  sections?:
    | {
        title: string;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  acknowledgment?: {
    heading?: string | null;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nodal-officers".
 */
export interface NodalOfficer {
  id: number;
  name: string;
  designation: string;
  organization: string;
  sector: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-leads-directory".
 */
export interface TrainingLeadsDirectory {
  id: number;
  name: string;
  designation?: string | null;
  organization: string;
  specialization?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload and manage gallery photos displayed on the Gallery page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items".
 */
export interface GalleryItem {
  id: number;
  /**
   * Caption shown below the image in the lightbox.
   */
  title: string;
  image: number | Media;
  category: 'industry-consultations' | 'training-capacity-building' | 'working-groups' | 'flagship-programs';
  /**
   * Optional short description shown in the lightbox.
   */
  description?: string | null;
  /**
   * Lower numbers appear first. Use to control display order.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'regulatory-updates';
        value: number | RegulatoryUpdate;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'news-items';
        value: number | NewsItem;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'nodal-officers';
        value: number | NodalOfficer;
      } | null)
    | ({
        relationTo: 'training-leads-directory';
        value: number | TrainingLeadsDirectory;
      } | null)
    | ({
        relationTo: 'gallery-items';
        value: number | GalleryItem;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageType?: T;
  banner?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
      };
  body?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              tagline?: T;
              heading?: T;
              headingHighlight?: T;
              headingTrail?: T;
              description?: T;
              primaryButton?:
                | T
                | {
                    label?: T;
                    link?: T;
                  };
              secondaryButton?:
                | T
                | {
                    label?: T;
                    link?: T;
                  };
              sideCard?:
                | T
                | {
                    strategicAlignmentText?: T;
                    industryLedText?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        capabilityMatrix?:
          | T
          | {
              sectionHeading?: T;
              sectionHeadingHighlight?: T;
              sectionDescription?: T;
              mandates?:
                | T
                | {
                    label?: T;
                    title?: T;
                    description?: T;
                    linkText?: T;
                    linkRef?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        regulatoryDashboard?:
          | T
          | {
              sectionEyebrow?: T;
              sectionHeading?: T;
              sectionDescription?: T;
              ctaText?: T;
              ctaLink?: T;
              viewCircularLabel?: T;
              id?: T;
              blockName?: T;
            };
        featuredPrograms?:
          | T
          | {
              sectionEyebrow?: T;
              sectionHeading?: T;
              sectionDescription?: T;
              viewAllText?: T;
              viewAllLink?: T;
              programs?:
                | T
                | {
                    title?: T;
                    category?: T;
                    description?: T;
                    link?: T;
                    image?: T;
                    id?: T;
                  };
              courseDetailsLabel?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              primaryButton?:
                | T
                | {
                    label?: T;
                    link?: T;
                  };
              secondaryButton?:
                | T
                | {
                    label?: T;
                    link?: T;
                  };
              id?: T;
              blockName?: T;
            };
        partnerships?:
          | T
          | {
              label?: T;
              heading?: T;
              description?: T;
              guidanceCard?:
                | T
                | {
                    label?: T;
                    title?: T;
                    logoUrl?: T;
                  };
              disclaimer?: T;
              id?: T;
              blockName?: T;
            };
      };
  whySection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        threats?:
          | T
          | {
              label?: T;
              id?: T;
            };
        alignedWith?:
          | T
          | {
              description?: T;
              items?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
            };
      };
  whatSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        focusAreas?:
          | T
          | {
              number?: T;
              title?: T;
              points?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  whoSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        ctaLabel?: T;
        ctaLink?: T;
        audiences?:
          | T
          | {
              name?: T;
              subtitle?: T;
              id?: T;
            };
      };
  membershipIntro?:
    | T
    | {
        subheading?: T;
        description?: T;
      };
  benefits?:
    | T
    | {
        category?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  responsibilities?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  validityTerms?:
    | T
    | {
        text?: T;
        id?: T;
      };
  feeTables?:
    | T
    | {
        turnoverBased?:
          | T
          | {
              tier?: T;
              fee?: T;
              id?: T;
            };
        aumBased?:
          | T
          | {
              tier?: T;
              fee?: T;
              id?: T;
            };
      };
  membershipCta?:
    | T
    | {
        label?: T;
        link?: T;
      };
  membershipSections?:
    | T
    | {
        benefitsEyebrow?: T;
        benefitsHeading?: T;
        benefitsDescription?: T;
        responsibilitiesEyebrow?: T;
        responsibilitiesHeading?: T;
        responsibilitiesDescription?: T;
        responsibilitiesDisclaimer?: T;
        validityEyebrow?: T;
        validityHeading?: T;
        feesEyebrow?: T;
        feesHeading?: T;
        feesDescription?: T;
        feeScheduleLabel?: T;
        turnoverLabel?: T;
        aumLabel?: T;
        feeSuffix?: T;
        turnoverColumnHeader?: T;
        aumColumnHeader?: T;
        feeColumnHeader?: T;
      };
  accessItems?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  learnersCta?:
    | T
    | {
        heading?: T;
        description?: T;
        buttonLabel?: T;
        buttonLink?: T;
      };
  learnersSection?:
    | T
    | {
        accessEyebrow?: T;
        accessHeading?: T;
        accessDescription?: T;
        ctaEyebrow?: T;
      };
  expertiseAreas?:
    | T
    | {
        label?: T;
        id?: T;
      };
  whyContribute?:
    | T
    | {
        heading?: T;
        points?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  contributorFormLabels?:
    | T
    | {
        personalInfoHeader?: T;
        contactDetailsHeader?: T;
        professionalBgHeader?: T;
        expertiseHeader?: T;
        expertiseInstruction?: T;
        contributionHeader?: T;
        contributionLabel?: T;
        contributionPlaceholder?: T;
        linkedinLabel?: T;
        linkedinPlaceholder?: T;
        submitLabel?: T;
        successHeading?: T;
        successEyebrow?: T;
        successDescription?: T;
        whyContributeHeader?: T;
        firstNameLabel?: T;
        lastNameLabel?: T;
        emailLabel?: T;
        phoneLabel?: T;
        organisationLabel?: T;
        designationLabel?: T;
        experienceLabel?: T;
        experienceOptions?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  pathwayTiers?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  certificationsUI?:
    | T
    | {
        filterTitle?: T;
        searchLabel?: T;
        searchPlaceholder?: T;
        levelLabel?: T;
        formatLabel?: T;
        clearFiltersLabel?: T;
        curriculumLabel?: T;
        liveLabel?: T;
        liveDescription?: T;
        comingSoonLabel?: T;
        noResultsMessage?: T;
      };
  formSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
      };
  contactInfo?:
    | T
    | {
        eyebrow?: T;
        entries?:
          | T
          | {
              label?: T;
              links?:
                | T
                | {
                    text?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  contactFormLabels?:
    | T
    | {
        successMessage?: T;
        errorMessage?: T;
        nameLabel?: T;
        namePlaceholder?: T;
        emailLabel?: T;
        emailPlaceholder?: T;
        phoneLabel?: T;
        phonePlaceholder?: T;
        subjectLabel?: T;
        subjectPlaceholder?: T;
        messageLabel?: T;
        messagePlaceholder?: T;
        submitLabel?: T;
        submittingLabel?: T;
      };
  membersLabels?:
    | T
    | {
        directoryEyebrow?: T;
        countLabel?: T;
        footerLabel?: T;
      };
  trainingLeadsContent?:
    | T
    | {
        sectionEyebrow?: T;
        sectionHeading?: T;
        sectionDescription?: T;
        numberHeader?: T;
        nameHeader?: T;
        organizationHeader?: T;
        specialisationHeader?: T;
        leadsCountLabel?: T;
        specialisationsCountLabel?: T;
        lastUpdated?: T;
      };
  nodalOfficersContent?:
    | T
    | {
        nodalOfficerLabel?: T;
        fallbackDesignation?: T;
        sectorsCountLabel?: T;
        officersCountLabel?: T;
        lastUpdated?: T;
      };
  updatesUI?:
    | T
    | {
        noResultsMessage?: T;
        emptyMessage?: T;
        viewCircularLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulatory-updates_select".
 */
export interface RegulatoryUpdatesSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  referenceNumber?: T;
  category?: T;
  issuingBody?: T;
  pdf?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  title?: T;
  level?: T;
  focus?: T;
  category?: T;
  format?: T;
  description?: T;
  curriculum?:
    | T
    | {
        item?: T;
        id?: T;
      };
  duration?: T;
  launchStatus?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-items_select".
 */
export interface NewsItemsSelect<T extends boolean = true> {
  text?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  contactEmail?: T;
  sections?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  acknowledgment?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nodal-officers_select".
 */
export interface NodalOfficersSelect<T extends boolean = true> {
  name?: T;
  designation?: T;
  organization?: T;
  sector?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-leads-directory_select".
 */
export interface TrainingLeadsDirectorySelect<T extends boolean = true> {
  name?: T;
  designation?: T;
  organization?: T;
  specialization?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items_select".
 */
export interface GalleryItemsSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  category?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes".
 */
export interface Programme {
  id: number;
  banner?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
  };
  sectionHeadings?: {
    engagementStrategy?: string | null;
    programmeSchedule?: string | null;
    recentConsultations?: string | null;
    annualMeetings?: string | null;
  };
  labels?: {
    activeChannelsLabel?: string | null;
    sessionsLabel?: string | null;
    institutionalDialogueEyebrow?: string | null;
    annualMeetingsDescription?: string | null;
    programmeTableHeader?: string | null;
    formatTableHeader?: string | null;
    timelineTableHeader?: string | null;
    yearTableHeader?: string | null;
    meetingTableHeader?: string | null;
    dateTableHeader?: string | null;
    locationTableHeader?: string | null;
  };
  engagementFormats?:
    | {
        title: string;
        description: string;
        points?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  programmeSchedule?:
    | {
        name: string;
        type: string;
        date: string;
        id?: string | null;
      }[]
    | null;
  recentConsultations?:
    | {
        name: string;
        type: string;
        date: string;
        id?: string | null;
      }[]
    | null;
  annualMeetings?:
    | {
        name: string;
        date: string;
        location: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navigation?:
    | {
        label: string;
        link: string;
        hasDropdown?: boolean | null;
        dropdownLabel?: string | null;
        dropdownItems?:
          | {
              label: string;
              description?: string | null;
              link: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  memberPortalLabel?: string | null;
  memberPortalUrl?: string | null;
  learnerPortalLabel?: string | null;
  learnerPortalUrl?: string | null;
  fiuLogoLink?: string | null;
  linkedinUrl?: string | null;
  loginLabel?: string | null;
  loginAsLabel?: string | null;
  organizationLoginLabel?: string | null;
  organizationLoginDescription?: string | null;
  learnerLoginLabel?: string | null;
  learnerLoginDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline?: string | null;
  initiativeLabel?: string | null;
  linkGroups?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  bottomLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteTitle?: string | null;
  siteDescription?: string | null;
  /**
   * Display labels for regulatory update categories (used on Updates and Home pages)
   */
  categoryLabels?:
    | {
        /**
         * Internal slug e.g. aml-cft
         */
        value: string;
        /**
         * Display label e.g. AML / CFT
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Display labels for issuing bodies (used on Updates and Home pages)
   */
  issuingBodyLabels?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the bottom sections of the Gallery page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page".
 */
export interface GalleryPage {
  id: number;
  aboutSection?: {
    title?: string | null;
    description?: string | null;
    features?:
      | {
          label: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  ctaSection?: {
    title?: string | null;
    description?: string | null;
    primaryButtonLabel?: string | null;
    primaryButtonLink?: string | null;
    secondaryButtonLabel?: string | null;
    secondaryButtonLink?: string | null;
  };
  importantNote?: {
    title?: string | null;
    text?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes_select".
 */
export interface ProgrammesSelect<T extends boolean = true> {
  banner?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
      };
  sectionHeadings?:
    | T
    | {
        engagementStrategy?: T;
        programmeSchedule?: T;
        recentConsultations?: T;
        annualMeetings?: T;
      };
  labels?:
    | T
    | {
        activeChannelsLabel?: T;
        sessionsLabel?: T;
        institutionalDialogueEyebrow?: T;
        annualMeetingsDescription?: T;
        programmeTableHeader?: T;
        formatTableHeader?: T;
        timelineTableHeader?: T;
        yearTableHeader?: T;
        meetingTableHeader?: T;
        dateTableHeader?: T;
        locationTableHeader?: T;
      };
  engagementFormats?:
    | T
    | {
        title?: T;
        description?: T;
        points?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  programmeSchedule?:
    | T
    | {
        name?: T;
        type?: T;
        date?: T;
        id?: T;
      };
  recentConsultations?:
    | T
    | {
        name?: T;
        type?: T;
        date?: T;
        id?: T;
      };
  annualMeetings?:
    | T
    | {
        name?: T;
        date?: T;
        location?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navigation?:
    | T
    | {
        label?: T;
        link?: T;
        hasDropdown?: T;
        dropdownLabel?: T;
        dropdownItems?:
          | T
          | {
              label?: T;
              description?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  memberPortalLabel?: T;
  memberPortalUrl?: T;
  learnerPortalLabel?: T;
  learnerPortalUrl?: T;
  fiuLogoLink?: T;
  linkedinUrl?: T;
  loginLabel?: T;
  loginAsLabel?: T;
  organizationLoginLabel?: T;
  organizationLoginDescription?: T;
  learnerLoginLabel?: T;
  learnerLoginDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  initiativeLabel?: T;
  linkGroups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  bottomLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  siteDescription?: T;
  categoryLabels?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  issuingBodyLabels?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page_select".
 */
export interface GalleryPageSelect<T extends boolean = true> {
  aboutSection?:
    | T
    | {
        title?: T;
        description?: T;
        features?:
          | T
          | {
              label?: T;
              description?: T;
              id?: T;
            };
      };
  ctaSection?:
    | T
    | {
        title?: T;
        description?: T;
        primaryButtonLabel?: T;
        primaryButtonLink?: T;
        secondaryButtonLabel?: T;
        secondaryButtonLink?: T;
      };
  importantNote?:
    | T
    | {
        title?: T;
        text?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}