/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    'regulatory-updates': RegulatoryUpdate;
    certifications: Certification;
    'news-items': NewsItem;
    members: Member;
    'legal-pages': LegalPage;
    'nodal-officers': NodalOfficer;
    'training-leads-directory': TrainingLeadsDirectory;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'regulatory-updates': RegulatoryUpdatesSelect<false> | RegulatoryUpdatesSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    'news-items': NewsItemsSelect<false> | NewsItemsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    'nodal-officers': NodalOfficersSelect<false> | NodalOfficersSelect<true>;
    'training-leads-directory': TrainingLeadsDirectorySelect<false> | TrainingLeadsDirectorySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    programmes: Programme;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    programmes: ProgrammesSelect<false> | ProgrammesSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  pageType:
    | 'simple'
    | 'home'
    | 'about'
    | 'contact'
    | 'membership'
    | 'learners'
    | 'contributor'
    | 'certifications'
    | 'updates';
  banner?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
  };
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  layout?:
    | (
        | {
            tagline: string;
            heading: string;
            headingHighlight?: string | null;
            headingTrail?: string | null;
            description: string;
            primaryButton: {
              label: string;
              link: string;
            };
            secondaryButton: {
              label: string;
              link: string;
            };
            sideCard?: {
              strategicAlignmentText?: string | null;
              industryLedText?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            stats: {
              label: string;
              value: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            sectionHeading: string;
            sectionHeadingHighlight?: string | null;
            sectionDescription?: string | null;
            mandates: {
              label: string;
              title: string;
              description: string;
              linkText: string;
              linkRef: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'capabilityMatrix';
          }
        | {
            sectionEyebrow?: string | null;
            sectionHeading: string;
            sectionDescription?: string | null;
            ctaText?: string | null;
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'regulatoryDashboard';
          }
        | {
            sectionEyebrow?: string | null;
            sectionHeading: string;
            sectionDescription?: string | null;
            viewAllText?: string | null;
            viewAllLink?: string | null;
            programs: {
              title: string;
              category: string;
              description: string;
              link: string;
              image?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredPrograms';
          }
        | {
            heading: string;
            description: string;
            primaryButton: {
              label: string;
              link: string;
            };
            secondaryButton?: {
              label?: string | null;
              link?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            label?: string | null;
            heading: string;
            description?: string | null;
            guidanceCard: {
              label?: string | null;
              title: string;
              logoUrl?: string | null;
            };
            disclaimer?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'partnerships';
          }
        | {
            label?: string | null;
            heading: string;
            description?: string | null;
            links?:
              | {
                  eyebrow: string;
                  title: string;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            stat: {
              value: string;
              description: string;
            };
            ctaLabel?: string | null;
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'community';
          }
      )[]
    | null;
  whySection?: {
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    threats?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    alignedWith?: {
      description?: string | null;
      items?:
        | {
            label: string;
            value: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  whatSection?: {
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    focusAreas?:
      | {
          number: string;
          title: string;
          points?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  whoSection?: {
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaLink?: string | null;
    audiences?:
      | {
          name: string;
          subtitle: string;
          id?: string | null;
        }[]
      | null;
  };
  membershipIntro?: {
    subheading?: string | null;
    description?: string | null;
  };
  benefits?:
    | {
        category: string;
        items?:
          | {
              title: string;
              description: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  responsibilities?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  validityTerms?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  feeTables?: {
    turnoverBased?:
      | {
          tier: string;
          fee: string;
          id?: string | null;
        }[]
      | null;
    aumBased?:
      | {
          tier: string;
          fee: string;
          id?: string | null;
        }[]
      | null;
  };
  membershipCta?: {
    label?: string | null;
    link?: string | null;
  };
  accessItems?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  learnersCta?: {
    heading?: string | null;
    description?: string | null;
    buttonLabel?: string | null;
    buttonLink?: string | null;
  };
  expertiseAreas?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  whyContribute?: {
    heading?: string | null;
    points?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  pathwayTiers?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulatory-updates".
 */
export interface RegulatoryUpdate {
  id: number;
  title: string;
  date: string;
  referenceNumber: string;
  category:
    | 'aml-cft'
    | 'kyc-cdd'
    | 'reporting'
    | 'digital-onboarding'
    | 'fraud-cyber'
    | 'sanctions'
    | 'compliance-governance';
  issuingBody: 'rbi' | 'fiu-ind' | 'sebi' | 'irdai';
  link?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  title: string;
  level: string;
  focus: string;
  category: 'Foundation' | 'Professional' | 'Specialist' | 'Strategic';
  format: string;
  description: string;
  curriculum?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  duration: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-items".
 */
export interface NewsItem {
  id: number;
  text: string;
  published: boolean;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  title: string;
  slug: string;
  contactEmail?: string | null;
  sections?:
    | {
        title: string;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  acknowledgment?: {
    heading?: string | null;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nodal-officers".
 */
export interface NodalOfficer {
  id: number;
  name: string;
  designation: string;
  organization: string;
  sector: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-leads-directory".
 */
export interface TrainingLeadsDirectory {
  id: number;
  name: string;
  designation?: string | null;
  organization: string;
  specialization?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'regulatory-updates';
        value: number | RegulatoryUpdate;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'news-items';
        value: number | NewsItem;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'nodal-officers';
        value: number | NodalOfficer;
      } | null)
    | ({
        relationTo: 'training-leads-directory';
        value: number | TrainingLeadsDirectory;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageType?: T;
  banner?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
      };
  body?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              tagline?: T;
              heading?: T;
              headingHighlight?: T;
              headingTrail?: T;
              description?: T;
              primaryButton?:
                | T
                | {
                    label?: T;
                    link?: T;
                  };
              secondaryButton?:
                | T
                | {
                    label?: T;
                    link?: T;
                  };
              sideCard?:
                | T
                | {
                    strategicAlignmentText?: T;
                    industryLedText?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        capabilityMatrix?:
          | T
          | {
              sectionHeading?: T;
              sectionHeadingHighlight?: T;
              sectionDescription?: T;
              mandates?:
                | T
                | {
                    label?: T;
                    title?: T;
                    description?: T;
                    linkText?: T;
                    linkRef?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        regulatoryDashboard?:
          | T
          | {
              sectionEyebrow?: T;
              sectionHeading?: T;
              sectionDescription?: T;
              ctaText?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        featuredPrograms?:
          | T
          | {
              sectionEyebrow?: T;
              sectionHeading?: T;
              sectionDescription?: T;
              viewAllText?: T;
              viewAllLink?: T;
              programs?:
                | T
                | {
                    title?: T;
                    category?: T;
                    description?: T;
                    link?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              primaryButton?:
                | T
                | {
                    label?: T;
                    link?: T;
                  };
              secondaryButton?:
                | T
                | {
                    label?: T;
                    link?: T;
                  };
              id?: T;
              blockName?: T;
            };
        partnerships?:
          | T
          | {
              label?: T;
              heading?: T;
              description?: T;
              guidanceCard?:
                | T
                | {
                    label?: T;
                    title?: T;
                    logoUrl?: T;
                  };
              disclaimer?: T;
              id?: T;
              blockName?: T;
            };
        community?:
          | T
          | {
              label?: T;
              heading?: T;
              description?: T;
              links?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    href?: T;
                    id?: T;
                  };
              stat?:
                | T
                | {
                    value?: T;
                    description?: T;
                  };
              ctaLabel?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
      };
  whySection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        threats?:
          | T
          | {
              label?: T;
              id?: T;
            };
        alignedWith?:
          | T
          | {
              description?: T;
              items?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
            };
      };
  whatSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        focusAreas?:
          | T
          | {
              number?: T;
              title?: T;
              points?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  whoSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        ctaLabel?: T;
        ctaLink?: T;
        audiences?:
          | T
          | {
              name?: T;
              subtitle?: T;
              id?: T;
            };
      };
  membershipIntro?:
    | T
    | {
        subheading?: T;
        description?: T;
      };
  benefits?:
    | T
    | {
        category?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  responsibilities?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  validityTerms?:
    | T
    | {
        text?: T;
        id?: T;
      };
  feeTables?:
    | T
    | {
        turnoverBased?:
          | T
          | {
              tier?: T;
              fee?: T;
              id?: T;
            };
        aumBased?:
          | T
          | {
              tier?: T;
              fee?: T;
              id?: T;
            };
      };
  membershipCta?:
    | T
    | {
        label?: T;
        link?: T;
      };
  accessItems?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  learnersCta?:
    | T
    | {
        heading?: T;
        description?: T;
        buttonLabel?: T;
        buttonLink?: T;
      };
  expertiseAreas?:
    | T
    | {
        label?: T;
        id?: T;
      };
  whyContribute?:
    | T
    | {
        heading?: T;
        points?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  pathwayTiers?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulatory-updates_select".
 */
export interface RegulatoryUpdatesSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  referenceNumber?: T;
  category?: T;
  issuingBody?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  title?: T;
  level?: T;
  focus?: T;
  category?: T;
  format?: T;
  description?: T;
  curriculum?:
    | T
    | {
        item?: T;
        id?: T;
      };
  duration?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-items_select".
 */
export interface NewsItemsSelect<T extends boolean = true> {
  text?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  contactEmail?: T;
  sections?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  acknowledgment?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nodal-officers_select".
 */
export interface NodalOfficersSelect<T extends boolean = true> {
  name?: T;
  designation?: T;
  organization?: T;
  sector?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-leads-directory_select".
 */
export interface TrainingLeadsDirectorySelect<T extends boolean = true> {
  name?: T;
  designation?: T;
  organization?: T;
  specialization?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes".
 */
export interface Programme {
  id: number;
  banner?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
  };
  sectionHeadings?: {
    engagementStrategy?: string | null;
    programmeSchedule?: string | null;
    recentConsultations?: string | null;
    annualMeetings?: string | null;
  };
  engagementFormats?:
    | {
        title: string;
        description: string;
        points?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  programmeSchedule?:
    | {
        name: string;
        type: string;
        date: string;
        id?: string | null;
      }[]
    | null;
  recentConsultations?:
    | {
        name: string;
        type: string;
        date: string;
        id?: string | null;
      }[]
    | null;
  annualMeetings?:
    | {
        name: string;
        date: string;
        location: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navigation?:
    | {
        label: string;
        link: string;
        hasDropdown?: boolean | null;
        dropdownLabel?: string | null;
        dropdownItems?:
          | {
              label: string;
              description?: string | null;
              link: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  memberPortalLabel?: string | null;
  memberPortalUrl?: string | null;
  learnerPortalLabel?: string | null;
  learnerPortalUrl?: string | null;
  fiuLogoLink?: string | null;
  linkedinUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline?: string | null;
  initiativeLabel?: string | null;
  linkGroups?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  bottomLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes_select".
 */
export interface ProgrammesSelect<T extends boolean = true> {
  banner?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
      };
  sectionHeadings?:
    | T
    | {
        engagementStrategy?: T;
        programmeSchedule?: T;
        recentConsultations?: T;
        annualMeetings?: T;
      };
  engagementFormats?:
    | T
    | {
        title?: T;
        description?: T;
        points?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  programmeSchedule?:
    | T
    | {
        name?: T;
        type?: T;
        date?: T;
        id?: T;
      };
  recentConsultations?:
    | T
    | {
        name?: T;
        type?: T;
        date?: T;
        id?: T;
      };
  annualMeetings?:
    | T
    | {
        name?: T;
        date?: T;
        location?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navigation?:
    | T
    | {
        label?: T;
        link?: T;
        hasDropdown?: T;
        dropdownLabel?: T;
        dropdownItems?:
          | T
          | {
              label?: T;
              description?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  memberPortalLabel?: T;
  memberPortalUrl?: T;
  learnerPortalLabel?: T;
  learnerPortalUrl?: T;
  fiuLogoLink?: T;
  linkedinUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  initiativeLabel?: T;
  linkGroups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  bottomLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}